-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.spectator CASCADE;

CREATE TABLE IF NOT EXISTS public.spectator
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    full_name character varying(50) NOT NULL,
    birthday date NOT NULL,
    gender character varying(10) NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(20) NOT NULL,
    phone character varying(20) NOT NULL,
    city_id bigint NOT NULL,
    fc_id bigint,
    PRIMARY KEY (id),
    CONSTRAINT email UNIQUE (email)
);

DROP TABLE IF EXISTS public.football_club CASCADE;

CREATE TABLE IF NOT EXISTS public.football_club
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying(50) NOT NULL,
    city_id bigint NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.stadium CASCADE;

CREATE TABLE IF NOT EXISTS public.stadium
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying(50) NOT NULL,
    city_id bigint NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.game CASCADE;

CREATE TABLE IF NOT EXISTS public.game
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    tournament character varying(50),
    scheduled_on timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    stadium_id bigint NOT NULL,
    host_team_id bigint NOT NULL,
    guest_team_id bigint NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON COLUMN public.game.status
    IS 'Possible values: Scheduled, Started, Finished, Cancelled';

DROP TABLE IF EXISTS public.ticket CASCADE;

CREATE TABLE IF NOT EXISTS public.ticket
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    status character varying(20) NOT NULL DEFAULT 'Issued',
    sector_label character varying(10) NOT NULL,
    seat_number bigint NOT NULL,
    distribution_date date,
    game_id bigint NOT NULL,
    spectator_id bigint,
    PRIMARY KEY (id)
);

COMMENT ON COLUMN public.ticket.status
    IS 'Possible values: Issued, Sold, Distributed, Granted, Returned';

DROP TABLE IF EXISTS public.city CASCADE;

CREATE TABLE IF NOT EXISTS public.city
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying(50) NOT NULL,
    region character varying(50) NOT NULL,
    country character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.stadium_sector CASCADE;

CREATE TABLE IF NOT EXISTS public.stadium_sector
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    label character varying(10) NOT NULL,
    seats bigint NOT NULL,
    status character varying(30) NOT NULL,
    stadium_id bigint NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON COLUMN public.stadium_sector.status
    IS 'Possible values: For_Guest_Fans, General, For_Host_Fans, VIP, For_Families ';

ALTER TABLE IF EXISTS public.spectator
    ADD FOREIGN KEY (fc_id)
    REFERENCES public.football_club (id) MATCH FULL
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.spectator
    ADD FOREIGN KEY (city_id)
    REFERENCES public.city (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.football_club
    ADD CONSTRAINT fc_city_fk FOREIGN KEY (city_id)
    REFERENCES public.city (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.stadium
    ADD CONSTRAINT stadium_city_fk FOREIGN KEY (city_id)
    REFERENCES public.city (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT game_stadium_fk FOREIGN KEY (stadium_id)
    REFERENCES public.stadium (id) MATCH FULL
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT game_host_team_fk FOREIGN KEY (host_team_id)
    REFERENCES public.football_club (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT game_guest_team_fk FOREIGN KEY (guest_team_id)
    REFERENCES public.football_club (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.ticket
    ADD CONSTRAINT ticket_game_fk FOREIGN KEY (game_id)
    REFERENCES public.game (id) MATCH FULL
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.ticket
    ADD CONSTRAINT ticket_spectator_fk FOREIGN KEY (spectator_id)
    REFERENCES public.spectator (id) MATCH FULL
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.stadium_sector
    ADD CONSTRAINT sector_stadium_fk FOREIGN KEY (stadium_id)
    REFERENCES public.stadium (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;

END;